version: "3.9"

services:
  redis:
    image: redis:${REDIS_TAG:?The redis image tag must be set}
    container_name: scraping-redis
    restart: always
    ports:
      - "${REDIS_PORT:-16379}:6379"
    volumes:
      - redisdata:/data
    networks:
      - scrapingnet
    profiles: [ "services" ]
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "5"

  postgres:
    image: postgres:${POSTGRES_TAG:?The postgres image tag must be set}
    container_name: scraping-postgres
    restart: always
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - scrapingnet
    profiles: [ "services" ]
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "5"

  selenium-hub:
    image: selenium/hub:4.1.4
    container_name: selenium-hub
    shm_size: 2gb
    restart: always
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - scrapingnet
    profiles: [ "services" ]
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "5"

  chrome:
    image: selenium/node-chrome:4.1.4-20220427
    container_name: chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    networks:
      - scrapingnet
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=3
      - NODE_MAX_SESSION=3
    profiles: [ "services" ]
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "5"

  edge:
    image: selenium/node-edge:4.1.4-20220427
    container_name: edge
    shm_size: 2gb
    depends_on:
      - selenium-hub
    networks:
      - scrapingnet
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=3
      - NODE_MAX_SESSION=3
    profiles: [ "services" ]
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "5"

  firefox:
    image: selenium/node-firefox:4.1.4
    container_name: firefox
    depends_on:
      - selenium-hub
    networks:
      - scrapingnet
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=3
      - NODE_MAX_SESSION=3
    profiles: [ "services" ]
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "5"

networks:
  scrapingnet:

volumes:
  pgdata:
  redisdata:

